name: tivio
description: A fresh, premium live TV experience.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  video_player: ^2.8.6
  chewie: ^1.8.1

flutter:
  uses-material-design: true
